[server]
fileWatcherType = "poll"
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 